### PR TITLE
frontend: allow deleting snippets in review

### LINKED ISSUE #156: Ability to correct snippet range
I can review the text of the snippet, but the range of the snippet in the log cannot be altered (and sometimes they are not visible too).

### PR DESCRIPTION
**Pull request by FrostyX**
Fixes #156

This will be useful for changing a location of a snippet, in case the new snippet should be over the previous one.

### CODE REVIEW

**Review by TomasTomecek — CHANGES_REQUESTED** [review]
I played with this and found 2 issues:

1. The delete button appears also on `How to fix the issue?` and `Why did the build fail?`. I don't think it should be there.
2. When I delete all snippets and submit it, I get 500:
   ```
   backend_1   |   File "/opt/log-detective-website/backend/src/api.py", line 400, in _parse_logs
   backend_1   |     if snippet["file"] == name and snippet["vote"] == 1:
   backend_1   |        ~~~~~~~^^^^^^^^
   backend_1   | KeyError: 'file'
   ```
   this is understandable though we should show an alert saying that at least one single snippet should be added.

Otherwise it looks great! Thanks, Jakub.

Edit: Adding a screenshot for the first point:
delete on all sections

**Comment by FrostyX** [comment]
Good catches, thank you very much @TomasTomecek

**Review by TomasTomecek — APPROVED** [review]
Tested locally and works well now!

Though I could submit a report with no snippets, but it's not really a problem - it's a better situation than wrong snippets.

**Comment by nforro** [comment]
Nice, I just found this after trying to create a new snippet spanning more lines than the original wrong (and downvoted) one during review. How long does it take to get to production?

**Comment by TomasTomecek** [comment]
> Nice, I just found this after trying to create a new snippet spanning more lines than the original wrong (and downvoted) one during review. How long does it take to get to production?

Thanks for the feedback! I'll deploy it to prod today or tomorrow, will ping you once it's available :)

**Pull request merged**
